import {arrayify} from 'tslint/lib/utils';

export class CityArray {

  cityArray: string[];

  constructor() {
    this.cityArray = ['Aachen',
                      'Aalen',
                      'Aarbergen',
                      'Abenberg',
                      'Abensberg',
                      'Abtsgmünd',
                      'Achern',
                      'Achim',
                      'Adelebsen',
                      'Adelsdorf',
                      'Adenau',
                      'Adendorf',
                      'Adlkofen',
                      'Adorf',
                      'Aerzen',
                      'Ahaus',
                      'Ahnsen',
                      'Ahrbrück',
                      'Ahrensburg',
                      'Ahrensfelde',
                      'Aichach',
                      'Aichtal',
                      'Aidlingen',
                      'Ainring',
                      'Aiterhofen',
                      'Albbruck',
                      'Albershausen',
                      'Albig',
                      'Albstadt',
                      'Aldenhoven',
                      'Aldingen',
                      'Alfdorf',
                      'Alfeld (Leine)',
                      'AlfterAllendorf',
                      'Allensbach',
                      'Allersberg',
                      'Alling',
                      'Allmersbach im Tal',
                      'Almdorf',
                      'Alpen',
                      'Alpirsbach',
                      'Alsbach-Hähnlein',
                      'Alsdorf',
                      'Alsenz',
                      'Alsfeld',
                      'Altbach',
                      'Altdorf',
                      'Altena',
                      'Altenahr',
                      'Altenberg',
                      'Altenberge',
                      'Altenbuch',
                      'Altenburg',
                      'Altendiez',
                      'Altenkirchen (Westerwald)',
                      'Altenkunstadt',
                      'Altenstadt',
                      'Altenstadt an der Waldnaab',
                      'Altensteig',
                      'Althegnenberg',
                      'Althengstett',
                      'Althütte',
                      'Altlußheim',
                      'Altmannstein',
                      'Altötting',
                      'Altrip',
                      'Alzenau',
                      'Alzey',
                      'Amberg',
                      'Amerang',
                      'Ammerbuch',
                      'Amöneburg',
                      'Amorbach',
                      'Ampfing',
                      'Andechs',
                      'Andernach',
                      'Angelbachtal',
                      'Ankum',
                      'Annaberg-Buchholz',
                      'Annweiler am Trifels',
                      'Ansbach',
                      'Apen',
                      'Apensen',
                      'Apolda',
                      'Appenweier',
                      'Arnsberg',
                      'Arnstadt',
                      'Arnstorf',
                      'Artern/Unstrut',
                      'Arzfeld',
                      'Asbach',
                      'Aschaffenburg',
                      'Ascheberg',
                      'Aschersleben',
                      'Aschheim',
                      'Aßlar',
                      'Aspach',
                      'Asperg',
                      'Attendorn',
                      'Au',
                      'Aue',
                      'Auerbach',
                      'Auetal',
                      'Augsburg',
                      'Auhausen',
                      'Aulendorf',
                      'Aumühle',
                      'Aurich',
                      'Aystetten'];
  }

}
